version: '3'

services:
  photoframe:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: photoframe
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./data/photoframe.db:/app/photoframe.db
      - ./data/images:/data/images
    env_file:
      - .env
    environment:
      - TZ=${TZ:-UTC}